### ISSUE TITLE
Roadmap to stable version

### ISSUE THREAD

**Issue by targos** [image-js/image-js-typescript#147]
- [ ] Minimal documentation with docusaurus with announcement blog post.
  - [ ] Create repository
  - [ ] Demo page with list of images to select, drag/drop (optional), or webcam (optional) and live script
  - [ ] Complex "tutorials" (optional)
  - [ ] Live examples on API docs
    - [ ] "raw" code
    - [ ] fixed code with editable variables/parameters
  - [ ] Blog post about new TypeScript rewrite with high-level description of the breaking changes.
  - [ ] Link to tsdoc
- [ ] Review parity of functionality with legacy version.
- [ ] Check if API is consistent
- [ ] Do some benchmarks
